### ISSUE TITLE
Feed generated with --dummy flag does not validate

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/osmtogtfs#26]
I just ran [feedvalidator.py](https://github.com/google/transitfeed/blob/master/feedvalidator.py) from Google's `transitfeed` project on the generated zipfile and it displays 24821 errors and 17117 warnings!

Here are the commands:

    $ osmtogtfs resources/osm/bremen-latest.osm.pbf  --dummy --zipfile o.zip
    $ python2.7 feedvalidator.py o.zip

**Comment by mehdisadeghi** [comment]
@carocad here is the output. Most of the errors are about missing values, e.g. agency_url.
[validation-results.zip](https://github.com/hiposfer/osmtogtfs/files/1542899/validation-results.zip)

**Comment by carocad** [comment]
@mehdisadeghi nice thing to have this tool already there

It is very helpful !

 A quick manual check on the bremen results shows that they are right. We are using the same trip id for week and weekend so I guess that is wrong. Although I cannot think of a good way to solve that right now since we use the same underlying relation id for that 😞

**Comment by mehdisadeghi** [comment]
@carocad I fixed some of those errors, see #27 please. This is an updated validation check:

[validation-results.zip](https://github.com/hiposfer/osmtogtfs/files/1557362/validation-results.zip)

**Comment by mehdisadeghi** [comment]
Done in #39
