### ISSUE TITLE
consider adding a "choose file" button on the web interface

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#72]
currently the web interface only allows putting a link as input however in the case of custom areas, it is more likely that the user has the file locally not remotely.

**Comment by carocad** [comment]
@mehdisadeghi I think I would approach the problem from a different direction

Instead of assuming that `o2g` is a CLI tool and that the website is a demo. Why dont we just make `o2g` be *always* a website?

Given that `o2g` uses some C libraries which require some custom configuration and knowledge of it, I think that making `o2g` a web application would free it from those contrains.

It would also allows us to focus on the webinterface solely instead of having two fronts of development and a web UI is always easier to grasp than a cli tool ;)

what do you think?

**Comment by mehdisadeghi** [comment]
I would say we need both :wink: 

A CLI tool is good because it is easier to install and try compared to a web app. More importantly, it can be used in scripts, chained commands, etc.

A website, on the other hand, could be extended in many different ways and deliver different purposes.

Moreover, `o2g` is the command line tool, but the library is called `osmtogtfs` and can be used in other python projects. This is how I have used it in the web app.

**Comment by carocad** [comment]
> Moreover, o2g is the command line tool, but the library is called osmtogtfs and can be used in other python projects. This is how I have used it in the web app.
 
Oh i didnt realize that you have already organized it that way.

Going back to the topic of whether or not to promote the webapp to its own project, I would say better not to (at least for the time being). From your description it looks like osmtogtfs is a multi-face project. So I would stick to them living in the same repo as long as they dont differ significantly.
